Repository KDT3-Final-6/final-project-FE, pull requests merged in 2023-04, with the labels that each got.

#81 Feature: 초기 리덕스 생성
  src/api/product.ts
  src/components/Group/CategoryList.tsx
  src/components/Group/ProductList.tsx
  src/components/Home/Curation.tsx
  src/components/Home/GroupTravel.tsx
  src/components/Home/ThemeTravel.tsx
  src/components/ProductDetail/RelatedProduct.tsx
  src/components/Theme/MonthProductList.tsx
  src/components/common/CardTypeItem.tsx
  src/components/common/Loading.tsx
  src/components/common/Select.tsx
  src/constants/messages.ts
  src/env.d.ts
  src/interfaces/product.ts
  src/interfaces/user.ts
  src/main.tsx
  src/pages/Admin/TransactionList.tsx
  src/pages/Mypage/WishList.tsx
  src/pages/Search/index.tsx
  src/pages/TransactionList/index.tsx
  src/reduxStore/loadingSlice.ts
  src/reduxStore/store.ts
  src/router.tsx
Labels: Status: In Progress, Type: Feature/Function

#82 Feat: 관리자 페이지 상품 리스트 마크업
  public/mockData/product.json
  src/constants/pathConst.ts
  src/pages/ProductsList/index.tsx
Labels: Priority: High, Type: Feature/Function

#83 Feature: 회원가입 기능 구현중
  src/api/product.ts
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/constants/apiUrlConst.ts
  src/pages/SignUp/index.tsx
Labels: Status: In Progress, Type: Bug/Function, Type: Feature/Function

#84 Feat: 지역별 카테고리 페이지 마크업
  public/images/district_banner.png
  src/components/Header.tsx
  src/components/ProductPage/CategoryList.tsx
  src/components/ProductPage/District/DistrictCheckTab.tsx
  src/components/ProductPage/District/ProductSlider.tsx
  src/components/ProductPage/ProductList.tsx
  src/components/common/CheckItem.tsx
  src/constants/pathConst.ts
  src/pages/Product/District.tsx
  src/pages/Product/Group.tsx
  src/pages/Product/Recommend.tsx
  src/pages/Product/Theme.tsx
  src/pages/Survey/Result.tsx
  src/router.tsx
  src/styles/root.ts
Labels: Priority: High, Type: Feature/Function

#86 Feat: 상품 상세 페이지 API 연결
  src/api/product.ts
  src/components/Home/TravelReview.tsx
  src/components/ProductDetail/Detail.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductDetail/TravelReview.tsx
  src/components/common/Review.tsx
  src/interfaces/product.ts
  src/interfaces/review.ts
  src/pages/Product/ProductDetail.tsx
  src/pages/Product/Theme.tsx
  src/utils/copyURL.ts
Labels: Priority: High, Type: Feature/Function

#87 Feature: 회원가입 페이지 기능 구현중
  src/components/common/CheckItem.tsx
  src/components/common/Input.tsx
  src/components/common/InputItem.tsx
  src/interfaces/user.ts
  src/pages/Login/index.tsx
  src/pages/Mypage/InfoEdit.tsx
  src/pages/SignUp/index.tsx
Labels: Type: Bug/Function, Type: Feature/Function

#89 Feat: 카테고리별 페이지 api 연결
  public/mockData/product.json
  src/api/product.ts
  src/components/Home/Curation.tsx
  src/components/Home/GroupTravel.tsx
  src/components/Home/ThemeTravel.tsx
  src/components/ProductDetail/RelatedProduct.tsx
  src/components/ProductPage/CategoryList.tsx
  src/components/ProductPage/GroupTabs.tsx
  src/components/ProductPage/MonthProductList.tsx
  src/components/ProductPage/ProductList.tsx
  src/components/ProductPage/ProductSlider.tsx
  src/components/Theme/MonthProductList.tsx
  src/components/common/CardTypeItem.tsx
  src/components/common/CheckItem.tsx
  src/constants/apiUrlConst.ts
  src/interfaces/product.ts
  src/pages/Mypage/WishList.tsx
  src/pages/Product/District.tsx
  src/pages/Product/Group.tsx
  src/pages/Product/ProductDetail.tsx
  src/pages/Product/Recommend.tsx
  src/pages/Product/Theme.tsx
  src/pages/ProductsList/index.tsx
  src/pages/Search/index.tsx
  src/pages/Survey/Result.tsx
Labels: Priority: High, Type: Feature/Function

#90 Feature: 회원가입 기능 구현중
  public/mockData/category.json
  src/components/Home/ThemeTravel.tsx
  src/components/common/ConceptTabs.tsx
  src/components/common/InputBox.tsx
  src/components/common/InputItem.tsx
  src/components/common/Select.tsx
  src/interfaces/user.ts
  src/pages/Mypage/InfoEdit.tsx
  src/pages/SignUp/index.tsx
  src/pages/Survey/index.tsx
Labels: Status: In Progress, Type: Feature/Function

#91 Feat: 카테고리 페이지 api 기능 구현
  src/components/Home/ThemeTravel.tsx
  src/components/ProductPage/District/DistrictCheckTab.tsx
  src/components/ProductPage/GroupTabs.tsx
  src/components/ProductPage/ProductList.tsx
  src/constants/districtTab.ts
  src/pages/Product/District.tsx
  src/pages/Product/Group.tsx
  src/pages/Product/Recommend.tsx
Labels: Priority: High, Type: Feature/Function

#93 Feature: 회원가입 취미 선택란 구현중
  src/components/common/CheckItem.tsx
  src/components/common/Select.tsx
  src/pages/Mypage/InfoEdit.tsx
  src/pages/SignUp/index.tsx
  src/utils/count.ts
Labels: Status: In Progress, Type: Feature/Function

#95 Feat: 관리자 페이지 & 사용자 페이지 슬라이더
  package-lock.json
  package.json
  src/api/product.ts
  src/components/ProductPage/CategoryList.tsx
  src/components/ProductPage/ProductList.tsx
  src/components/common/Paginate.tsx
  src/components/common/SlideButtons.tsx
  src/constants/apiUrlConst.ts
  src/hooks/useSwiperSetting.ts
  src/pages/ProductsList/index.tsx
  src/styles/paginate.css
Labels: Priority: High, Type: Feature/Function

#96 Feature: 회원가입 완료
  src/api/auth.ts
  src/components/common/InputBox.tsx
  src/components/common/InputItem.tsx
  src/pages/SignUp/index.tsx
Labels: Priority: High, Type: Bug/Function, Type: Feature/Function

#99 Feat: API 연결 및 기능 구현
  src/api/instance.ts
  src/api/product.ts
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductDetail/TravelReview.tsx
  src/components/common/Review.tsx
  src/components/common/Select.tsx
  src/constants/apiUrlConst.ts
  src/interfaces/product.ts
  src/interfaces/review.ts
  src/pages/AddProduct/index.tsx
  src/pages/EditProduct/index.tsx
Labels: Priority: High, Type: Feature/Function

#100 Feature & Fix: 회원가입 모달창 적용 및 기능구현 에러 수정중
  package-lock.json
  package.json
  src/App.tsx
  src/api/auth.ts
  src/components/common/CheckItem.tsx
  src/components/common/ModalBox.tsx
  src/constants/messages.ts
  src/pages/Buy/index.tsx
  src/pages/SignUp/index.tsx
  src/reduxStore/loadingSlice.ts
  src/reduxStore/modalSlice.ts
  src/reduxStore/store.ts
Labels: Status: In Progress, Priority: High, Type: Bug/Function, Type: Feature/Function

#101 Feature: 로그인 완료
  src/api/auth.ts
  src/components/MyPage/SelectItemModal.tsx
  src/components/common/CheckItem.tsx
  src/components/common/Input.tsx
  src/components/common/ModalBox.tsx
  src/constants/messages.ts
  src/interfaces/user.ts
  src/pages/Login/index.tsx
  src/pages/SignUp/index.tsx
  src/reduxStore/modalSlice.ts
Labels: Status: In Progress, Priority: High, Type: Bug/Function, Type: Feature/Function

#102 Feat: 상품 상세 페이지 최근 본 상품 기능 구현
  src/App.tsx
  src/components/ProductDetail/CurrentProduct.tsx
  src/components/ProductDetail/RelatedProduct.tsx
  src/components/ProductDetail/TravelReview.tsx
  src/components/common/CardTypeItem.tsx
  src/interfaces/product.ts
  src/pages/Product/ProductDetail.tsx
Labels: Priority: High, Type: Feature/Function

#103 Fix: 회원가입 boolean 타입이 string 타입으로 넘어가는 현상 수정
  src/components/common/CheckItem.tsx
  src/pages/SignUp/index.tsx
Labels: Type: Bug/Function

#104 Feat: 상품 상세 페이지 장바구니 기능 구현
  src/api/product.ts
  src/components/ProductDetail/Detail.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/interfaces/product.ts
  src/pages/Product/ProductDetail.tsx
Labels: Priority: High, Type: Feature/Function

#106 Feature: 쿠키를 이용한 유저동기화 진행중
  src/App.tsx
  src/api/auth.ts
  src/components/Header.tsx
  src/components/common/Input.tsx
  src/components/common/InputItem.tsx
  src/components/common/ModalBox.tsx
  src/constants/apiUrlConst.ts
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/Mypage/InfoEdit.tsx
  src/pages/SignUp/index.tsx
  src/reduxStore/modalSlice.ts
  src/utils/cookie.ts
Labels: Status: In Progress, Type: Bug/Function, Type: Feature/Function

#108 Feat: 지역별 카테고리, 마이 페이지 기능 구현
  src/api/auth.ts
  src/api/mypage.ts
  src/api/product.ts
  src/components/MyPage/CartTable.tsx
  src/components/MyPage/MenuTab.tsx
  src/components/MyPage/ReviewBox.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductPage/CategoryList.tsx
  src/components/common/ModalBox.tsx
  src/constants/messages.ts
  src/constants/pathConst.ts
  src/hooks/useCounter.ts
  src/interfaces/product.ts
  src/interfaces/review.ts
  src/pages/Cart/index.tsx
  src/pages/Mypage/Cart.tsx
  src/pages/Mypage/CheckPassword.tsx
  src/pages/Mypage/InfoEdit.tsx
  src/pages/Mypage/MyReview.tsx
  src/pages/Mypage/index.tsx
  src/pages/Product/District.tsx
  src/reduxStore/cartSlice.ts
  src/router.tsx
Labels: Priority: High, Type: Feature/Function

#110 Feature: 토큰값 만료시, 자동 로그아웃 구현중
  package-lock.json
  package.json
  src/components/Header.tsx
  src/components/common/Loading.tsx
  src/constants/messages.ts
  src/lotties/loading.json
  src/pages/Login/index.tsx
Labels: Status: In Progress, Type: Bug/Function, Type: Feature/Function

#114 Hyerim
  src/api/auth.ts
  src/constants/messages.ts
  src/pages/Login/index.tsx
Labels: Priority: Low, Type: Feature/Function

#115 Feature: 관리자 로그인 시, 관리자 설정버튼 활성화
  src/components/Header.tsx
  src/pages/Login/index.tsx
  src/router.tsx
Labels: Priority: Medium, Type: Feature/Function

#116 Feature: 마이페이지 프로필 유저권한 표시
  src/interfaces/user.ts
  src/pages/Mypage/index.tsx
  src/styles/paginate.css
Labels: Priority: Low, Type: Feature/Function

#117 Fix: 보이지 않는 로딩 애니메이션 수정
  src/App.tsx
  src/components/Header.tsx
  src/components/common/Loading.tsx
  src/lotties/loadingLottie.json
Labels: Priority: Medium, Type: Bug/UI

#119 Feat: 장바구니 api 기능 구현
  package-lock.json
  package.json
  src/api/mypage.ts
  src/components/Home/ThemeTravel.tsx
  src/components/MyPage/CartTable.tsx
  src/components/MyPage/ReviewBox.tsx
  src/components/ProductDetail/CurrentProduct.tsx
  src/components/ProductDetail/MoveTab.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductDetail/TravelReview.tsx
  src/components/common/SlideButtons.tsx
  src/constants/messages.ts
  src/hooks/useCounter.ts
  src/interfaces/product.ts
  src/pages/EditProduct/index.tsx
  src/pages/Mypage/Cart.tsx
  src/pages/Mypage/MyReview.tsx
  src/pages/Product/ProductDetail.tsx
  src/reduxStore/api/cartApiSlice.ts
  src/reduxStore/cartSlice.ts
  src/reduxStore/rootReducer.ts
  src/reduxStore/store.ts
Labels: Priority: High, Type: Feature/Function

#120 Feature: 로그인 시, 회원정보 저장
  src/pages/Login/index.tsx
  src/reduxStore/features/userInfoSlice.ts
Labels: Priority: High, Type: Feature/Function

#121 Fix: 마이페이지 유저권한 쿠키로 설정
  src/pages/Mypage/index.tsx
Labels: Type: Bug/Function

#123 Feat: 설문조사 페이지 api 연결 및 기능 구현
  src/api/survey.ts
  src/components/Home/Curation.tsx
  src/components/Survey/Item.tsx
  src/constants/apiUrlConst.ts
  src/constants/surveyItems.ts
  src/interfaces/survey.ts
  src/pages/AddProduct/index.tsx
  src/pages/Survey/Result.tsx
  src/pages/Survey/index.tsx
  src/reduxStore/api/cartApiSlice.ts
  src/reduxStore/api/qnaApiSlice.ts
Labels: Priority: High, Type: Feature/Function

#127 Fix: 유저정보 에러 수정
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/Mypage/CheckPassword.tsx
  src/pages/Mypage/InfoEdit.tsx
  src/reduxStore/features/userInfoSlice.ts
Labels: Priority: Critical, Type: Bug/Function

#128 Feature: rootReducer 인터페이스 생성
  src/interfaces/rootReducer.ts
  src/pages/Mypage/InfoEdit.tsx
Labels: Priority: High, Type: Feature/Function

#129 Design: 검색페이지에선 헤더 검색바 삭제
  src/components/Header.tsx
  src/pages/Search/index.tsx
  src/utils/isCurlPath.ts
Labels: Type: Feature/Function

#131 Feat: 장바구니, 설문조사 기능 구현
  src/App.tsx
  src/components/MyPage/CartTable.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/common/Image.tsx
  src/constants/surveyItems.ts
  src/pages/Mypage/Cart.tsx
  src/pages/Product/ProductDetail.tsx
  src/pages/Survey/Result.tsx
  src/pages/Survey/index.tsx
Labels: Priority: High, Type: Feature/Function

#132 Feat: 상품 상세 페이지 & 관리자 페이지
  src/api/auth.ts
  src/api/product.ts
  src/components/Header.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/common/HeartButton.tsx
  src/constants/apiUrlConst.ts
  src/interfaces/product.ts
  src/interfaces/wishlist.ts
  src/pages/Login/index.tsx
  src/pages/Mypage/WishList.tsx
  src/pages/Mypage/index.tsx
  src/pages/Product/ProductDetail.tsx
  src/pages/ProductsList/index.tsx
  src/reduxStore/store.ts
Labels: Priority: High, Type: Feature/Function

#133 Feature: 회원정보수정 테스트중
  src/App.tsx
  src/api/auth.ts
  src/components/Header.tsx
  src/components/MyPage/MenuTab.tsx
  src/components/common/Input.tsx
  src/components/common/InputItem.tsx
  src/components/common/Select.tsx
  src/constants/messages.ts
  src/constants/pathConst.ts
  src/interfaces/user.ts
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/Mypage/InfoEdit.tsx
  src/pages/SignUp/index.tsx
Labels: Status: In Progress, Priority: High, Type: Bug/Function, Type: Bug/UI, Type: Feature/Function

#136 Feat: 리뷰 모달 구현 중 & removeCookies 수정
  src/App.tsx
  src/api/mypage.ts
  src/components/Header.tsx
  src/components/MyPage/OrderBox.tsx
  src/components/MyPage/OrderCard.tsx
  src/components/MyPage/OrderDetailCard.tsx
  src/components/MyPage/ReviewBox.tsx
  src/components/ProductDetail/TravelReview.tsx
  src/components/common/ReviewModal.tsx
  src/constants/surveyItems.ts
  src/pages/Mypage/Cart.tsx
  src/pages/Mypage/MyReview.tsx
  src/pages/Mypage/OrderList.tsx
  src/pages/Survey/Result.tsx
  src/reduxStore/api/cartApiSlice.ts
  src/reduxStore/api/reviewApiSlice.ts
  src/reduxStore/reviewModalSlice.ts
  src/reduxStore/rootReducer.ts
  src/reduxStore/store.ts
Labels: Priority: Critical, Type: Feature/Function

#137 Feature: 경로보호 컴포넌트 생성
  src/constants/messages.ts
  src/main.tsx
  src/pages/Login/index.tsx
  src/routes/PrivateRoute.tsx
  src/routes/router.tsx
Labels: Priority: High, Type: Feature/Function

#139 Fix: 회원가입수정 테스트 완료
  src/components/Header.tsx
  src/components/common/Loading.tsx
  src/components/common/ModalBox.tsx
  src/interfaces/rootReducer.ts
  src/pages/Mypage/InfoEdit.tsx
Labels: Type: Bug/Function

#140 Fix: 로그아웃 에러 해결
  public/images/themeAmen.jpg
  public/images/themeCulture.jpg
  public/images/themeGolf.png
  public/images/themeTracking.jpg
  public/images/themeVacation.jpg
  src/components/Header.tsx
  src/components/Home/ThemeTravel.tsx
  src/lotties/notFoundLottie.json
  src/pages/NotFound/index.tsx
  src/pages/PostList/index.tsx
  src/pages/UserList/index.tsx
  src/styles/GlobalStyle.tsx
Labels: Priority: High, Type: Bug/Function, Type: Bug/UI, Type: Feature/Function

#141 Feat: 리뷰 모달 기능 구현 중
  package-lock.json
  src/components/MyPage/OrderDetailCard.tsx
  src/components/MyPage/ReviewBox.tsx
  src/components/common/ReviewModal.tsx
  src/pages/Search/index.tsx
  src/reduxStore/api/reviewApiSlice.ts
  src/reduxStore/reviewModalSlice.ts
Labels: Priority: High, Type: Feature/Function

#143 Feature: 관리자페이지 거래내역 페이지 구현중
  src/api/auth.ts
  src/api/transaction.ts
  src/components/Header.tsx
  src/constants/apiUrlConst.ts
  src/constants/messages.ts
  src/interfaces/transaction.ts
  src/interfaces/user.ts
  src/pages/Admin/TransactionList.tsx
  src/pages/Mypage/CheckPassword.tsx
  src/pages/Mypage/InfoEdit.tsx
  src/reduxStore/features/userInfoSlice.ts
Labels: Status: In Progress, Type: Bug/Function, Type: Feature/Function

#144 Feat: 관리자 페이지 상품 추가 기능 구
  src/api/instance.ts
  src/api/product.ts
  src/components/MyPage/ReviewBox.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/common/CardTypeItem.tsx
  src/pages/AddProduct/index.tsx
  src/pages/Mypage/WishList.tsx
Labels: Priority: High, Type: Feature/Function

#145 Feat: 관리자 페이지 상품 삭제 기능 구현
  src/interfaces/product.ts
  src/pages/ProductsList/index.tsx
  src/reduxStore/api/adminProductApiSlice.ts
  src/reduxStore/rootReducer.ts
  src/reduxStore/store.ts
Labels: Priority: High, Type: Feature/Function

#146 Feature: 관리자 거래내역 진행중
  src/interfaces/transaction.ts
  src/pages/Admin/TransactionList.tsx
Labels: Status: In Progress, Type: Feature/Function

#148 Feat: 찜 기능, 리뷰 기능 구현
  src/api/product.ts
  src/components/Admin/ProductForm.tsx
  src/components/Home/TravelReview.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductPage/CategoryList.tsx
  src/components/ProductPage/MonthProductList.tsx
  src/components/ProductPage/ProductList.tsx
  src/components/common/CardTypeItem.tsx
  src/components/common/Review.tsx
  src/pages/AddProduct/index.tsx
  src/pages/EditProduct/Option.tsx
  src/pages/EditProduct/index.tsx
  src/pages/Mypage/WishList.tsx
  src/pages/ProductsList/index.tsx
  src/reduxStore/api/reviewApiSlice.ts
  src/reduxStore/api/wishlistApislice.ts
  src/reduxStore/rootReducer.ts
  src/reduxStore/store.ts
Labels: Priority: High, Type: Feature/Function

#150 Feat: 헤더 및 프라이빗 라우터 설정
  src/components/Header.tsx
  src/components/Home/TravelReview.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/constants/pathConst.ts
  src/pages/Contact/index.tsx
  src/pages/Review/index.tsx
  src/pages/User/index.tsx
  src/routes/router.tsx
Labels: Priority: High, Type: Feature/Function

#151 Feat: 찜하기 기능, 에러 처리 정리
  src/components/ProductPage/MonthProductList.tsx
  src/components/ProductPage/ProductList.tsx
  src/components/common/Review.tsx
  src/constants/messages.ts
  src/pages/Mypage/OneOnOne.tsx
  src/pages/Mypage/OrderList.tsx
  src/pages/Mypage/WishList.tsx
  src/pages/ProductsList/index.tsx
  src/routes/AdminRoute.tsx
  src/routes/router.tsx
Labels: Priority: High, Type: Feature/Function

#152 Feat: 관리자페이지 - 회원관리페이지, 게시물관리페이지 기능구현
  public/images/icons/arrow_top.png
  public/images/nonUser.png
  src/components/Admin/AnswerCard.tsx
  src/components/Admin/FilterSelect.tsx
  src/components/Admin/PostCard.tsx
  src/components/Admin/UserCard.tsx
  src/components/MyPage/QnASelectBtn.tsx
  src/constants/apiUrlConst.ts
  src/interfaces/adminPost.ts
  src/interfaces/adminUsers.ts
  src/pages/Buy/index.tsx
  src/pages/PostList/index.tsx
  src/pages/Search/index.tsx
  src/pages/UserList/index.tsx
  src/reduxStore/api/adminPostApiSlice.ts
  src/reduxStore/api/adminUserApiSlice.ts
  src/reduxStore/features/userInfoSlice.ts
  src/reduxStore/rootReducer.ts
  src/reduxStore/store.ts
Labels: Priority: High, Type: Feature/Function

#155 Feat: 메인 모바일 반응형 마크업
  package-lock.json
  package.json
  public/images/mobile_logo.png
  src/App.tsx
  src/components/Mobile/MFloating.tsx
  src/components/Mobile/MFooter.tsx
  src/components/Mobile/MHeader.tsx
  src/components/common/Pagination.tsx
Labels: Priority: High, Type: Feature/Function

#156 Feature: 인스턴스 수정
  .gitignore
  src/api/instance.ts
  src/interfaces/transaction.ts
  src/pages/Admin/TransactionList.tsx
  src/pages/Login/index.tsx
  src/routes/router.tsx
Labels: Status: In Progress, Priority: High, Priority: Critical, Type: Bug/UI, Type: Feature/Function

#159 Feature: 메인 그룹별여행 완료
  package-lock.json
  package.json
  src/api/instance.ts
  src/api/product.ts
  src/api/refresh.ts
  src/components/Home/GroupTravel.tsx
  src/components/common/ConceptTabs.tsx
  src/components/common/GroupTabs.tsx
  src/pages/Admin/TransactionList.tsx
  src/pages/Login/index.tsx
Labels: Priority: Critical, Type: Bug/Function, Type: Bug/UI, Type: Feature/Function

#163 Refactor: 관리자 페이지 라우터 수정
  src/routes/AdminRoute.tsx
  src/routes/router.tsx
Labels: Priority: Critical, Type: Feature/Function

#166 Feature: 관리자 거래내역 Query 생성
  src/api/transaction.ts
  src/components/Admin/TransactionCon.tsx
  src/components/Header.tsx
  src/components/Home/GroupTravel.tsx
  src/constants/apiUrlConst.ts
  src/constants/pathConst.ts
  src/interfaces/transaction.ts
  src/pages/Admin/TransactionList.tsx
  src/reduxStore/api/adminTransactionApiSlice.ts
  src/reduxStore/rootReducer.ts
  src/reduxStore/store.ts
  src/routes/router.tsx
Labels: Status: In Progress, Type: Feature/Function

#167 Hyerim
  src/components/MyPage/MenuTab.tsx
  src/pages/Admin/TransactionList.tsx
  src/routes/router.tsx
Labels: Status: In Progress, Type: Bug/Function

#169 Feat: 헤더 로그인 함수 수정
  src/components/Header.tsx
  src/interfaces/user.ts
  src/pages/Login/index.tsx
  src/pages/Mypage/InfoEdit.tsx
  src/pages/Mypage/index.tsx
  src/reduxStore/api/userApiSlice.ts
  src/reduxStore/features/userInfoSlice.ts
  src/reduxStore/rootReducer.ts
  src/reduxStore/store.ts
  src/routes/router.tsx
  src/utils/isCurlPath.ts
Labels: Priority: High, Type: Feature/Function

#172 Refactor: 로그인 api rtk-query로 수정
  src/components/Header.tsx
  src/interfaces/user.ts
  src/pages/Mypage/InfoEdit.tsx
  src/pages/SignUp/index.tsx
  src/pages/Survey/Result.tsx
  src/reduxStore/api/userApiSlice.ts
Labels: Priority: High, Type: Feature/Function

#175 Test: 찜 기능 rtk-query 테스트 중
  src/components/Home/GroupTravel.tsx
  src/components/Home/ThemeTravel.tsx
  src/components/ProductDetail/CurrentProduct.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductDetail/RelatedProduct.tsx
  src/components/ProductDetail/TravelReview.tsx
  src/components/ProductPage/CategoryList.tsx
  src/components/ProductPage/MonthProductList.tsx
  src/components/ProductPage/ProductList.tsx
  src/hooks/useSwiperSetting.ts
  src/pages/Product/Group.tsx
  src/pages/Product/ProductDetail.tsx
  src/reduxStore/api/productsApiSlice.ts
  src/reduxStore/api/wishlistApislice.ts
  src/reduxStore/rootReducer.ts
  src/reduxStore/store.ts
Labels: Priority: High, Type: Feature/Function

#177 Refactor: 사용하지 않는 axios 코드 정리
  src/api/auth.ts
  src/api/instance.ts
  src/api/mypage.ts
  src/api/post.ts
  src/api/product.ts
  src/components/Home/ThemeTravel.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductDetail/RelatedProduct.tsx
  src/components/ProductPage/ProductList.tsx
  src/pages/Product/District.tsx
  src/pages/Product/ProductDetail.tsx
  src/pages/Product/Recommend.tsx
  src/pages/Product/Theme.tsx
  src/pages/SignUp/index.tsx
  src/reduxStore/api/cartApiSlice.ts
  src/reduxStore/api/productsApiSlice.ts
  src/utils/getSelected.ts
Labels: Priority: Critical

#185 Feat: 관리자 페이지 상품 관리
  src/pages/EditProduct/Option.tsx
  src/reduxStore/api/adminProductApiSlice.ts
Labels: Priority: High, Type: Feature/Function

#186 Feat: 관리자 페이지 상품 추가 및 수정
  src/components/Admin/ProductForm.tsx
  src/components/Header.tsx
Labels: Priority: High, Type: Feature/Function
