Repository KDT3-Final-6/final-project-FE, pull requests merged in 2023-03, with the labels that each got.

#3 Docs: pr 템플릿
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  tsconfig.json
Labels: Priority: Critical

#4 Env: 파일트리 설정
  .vscode/extensions.json
  src/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/constants/messages.ts
  src/constants/pathConst.ts
  src/interfaces/login.ts
  src/interfaces/signup.ts
  src/pages/Cart/index.tsx
  src/pages/Contact/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/Product/index.tsx
  src/pages/Review/index.tsx
  src/pages/Search/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/Survey/index.tsx
  src/pages/User/index.tsx
  src/router.tsx
Labels: Type: Feature/Document

#5 Test: pr 템플릿
  pull_request_template.md
Labels: Priority: Critical

#9 Feat: 상품 상세 페이지 UXUI 마크업
  README.md
  package-lock.json
  package.json
  public/_redirects
  src/components/ProductDetail/Detail.tsx
  src/components/ProductDetail/MoveTab.tsx
  src/components/ProductDetail/Option.tsx
  src/components/ProductDetail/ProductCard.tsx
  src/components/ProductDetail/ProductCards.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductDetail/Review.tsx
  src/components/ProductDetail/Reviews.tsx
  src/constants/pathConst.ts
  src/index.css
  src/main.tsx
  src/pages/Product/ProductDetail.tsx
  src/router.tsx
Labels: Status: In Progress, Priority: Medium, Type: Feature/Function

#10 Chore: swiper, paginate 설치
  package-lock.json
  package.json
Labels: Priority: Critical, Type: Feature/Function, Status: Duplicated

#11 Design: 글로벌 스타일 설정중
  public/images/Logo_Gotogether.png
  src/App.tsx
  src/assets/react.svg
  src/components/ProductDetail/ProductCard.tsx
  src/components/ProductDetail/ProductCards.tsx
  src/components/ProductDetail/Review.tsx
  src/components/ProductDetail/Reviews.tsx
  src/index.css
  src/layout/Inner.tsx
  src/pages/Product/ProductDetail.tsx
  src/styles/GlobalStyle.tsx
Labels: Type: Feature/Function

#16 Feature: 헤더 완료 & Input, Button 컴포넌트 추가
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/ProductDetail/ProductCards.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/SecondaryTitle.tsx
  src/index.css
  src/layout/Inner.tsx
  src/styles/GlobalStyle.tsx
  src/styles/root.ts
Labels: Type: Feature/Function

#18 Feature: Title 컴포넌트 수정 및 적용
  src/components/ProductDetail/ProductCards.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/common/Input.tsx
  src/components/common/SecondaryTitle.tsx
  src/components/common/Title.tsx
Labels: Priority: High, Type: Feature/Function

#19 Feature: 푸터 영역 완료
  package-lock.json
  package.json
  public/images/Logo_footer.png
  src/components/Footer.tsx
  src/components/Header.tsx
  src/pages/Home/index.tsx
  src/pages/Product/ProductDetail.tsx
  src/styles/root.ts
Labels: Type: Feature/Function

#20 Feature: Home 페이지 section별 생성
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Home/Curation.tsx
  src/components/Home/GroupTravel.tsx
  src/components/Home/SlideBanner.tsx
  src/components/Home/ThemeTravel.tsx
  src/components/Home/TravelEvent.tsx
  src/components/Home/TravelReview.tsx
  src/components/common/Button.tsx
  src/layout/Inner.tsx
  src/layout/Section.tsx
  src/pages/Home/index.tsx
Labels: Type: Feature/Function

#21 Feat: 마이 페이지 UXUI 마크업
  public/images/myPage_banner.png
  public/images/profile.png
  src/components/Footer.tsx
  src/components/MyPage/MenuTab.tsx
  src/components/MyPage/OrderCard.tsx
  src/components/ProductDetail/MoveTab.tsx
  src/components/ProductDetail/Option.tsx
  src/components/ProductDetail/ProductCard.tsx
  src/components/ProductDetail/ProductCards.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductDetail/Review.tsx
  src/components/common/RoundButton.tsx
  src/constants/pathConst.ts
  src/index.css
  src/pages/Mypage/Cart.tsx
  src/pages/Mypage/InfoEdit.tsx
  src/pages/Mypage/MyReview.tsx
  src/pages/Mypage/OneOnOne.tsx
  src/pages/Mypage/OrderList.tsx
  src/pages/Mypage/WishList.tsx
  src/pages/Mypage/index.tsx
  src/router.tsx
Labels: Status: Review Needed, Priority: High, Type: Feature/Function

#23 Fix: 로고 경로 수정
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Home/Curation.tsx
  src/components/Home/GroupTravel.tsx
  src/components/MyPage/MenuTab.tsx
  src/components/ProductDetail/ProductCards.tsx
  src/components/common/Button.tsx
  src/components/common/ProductCard.tsx
  src/pages/Mypage/OrderList.tsx
  src/pages/Mypage/index.tsx
  src/styles/root.ts
Labels: Type: Bug/UI, Type: Feature/Function

#29 Fix: 상품 카드 이미지 영역 수정
  src/components/Home/Curation.tsx
  src/components/Home/GroupTravel.tsx
  src/components/common/ProductCard.tsx
Labels: Type: Bug/UI

#31 Feat: 마이 페이지 라우터 변경
  src/components/MyPage/CartTable.tsx
  src/components/MyPage/MenuTab.tsx
  src/components/common/Button.tsx
  src/components/common/RoundButton.tsx
  src/constants/pathConst.ts
  src/pages/Mypage/Cart.tsx
  src/pages/Mypage/index.tsx
  src/router.tsx
Labels: Priority: High, Type: Feature/Function

#32 Feature: 바타입 & 카드타입 컴포넌트 생성 및 적용
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Home/Curation.tsx
  src/components/Home/GroupTravel.tsx
  src/components/Home/KV/Slide.tsx
  src/components/Home/ThemeTravel.tsx
  src/components/Home/TravelEvent.tsx
  src/components/Home/TravelReview.tsx
  src/components/MyPage/MenuTab.tsx
  src/components/MyPage/WishListItem.tsx
  src/components/ProductDetail/MoveTab.tsx
  src/components/ProductDetail/Option.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductDetail/Review.tsx
  src/components/common/BarTypeItem.tsx
  src/components/common/Button.tsx
  src/components/common/CardTypeItem.tsx
  src/components/common/CheckBox.tsx
  src/components/common/HeartButton.tsx
  src/components/common/Input.tsx
  src/components/common/ProductCard.tsx
  src/components/common/RoundButton.tsx
  src/components/common/Title.tsx
  src/index.css
  src/interfaces/order.ts
  src/interfaces/product.ts
  src/layout/Inner.tsx
  src/layout/Section.tsx
  src/main.tsx
  src/pages/Login/index.tsx
  src/pages/Mypage/OrderList.tsx
  src/pages/Mypage/WishList.tsx
  src/pages/Mypage/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/root.ts
Labels: Type: Feature/Function

#34 Feat: 마이 페이지 장바구니 UXUI 마크업
  index.html
  public/images/cart_image (1).jpg
  public/images/cart_image (2).jpg
  src/components/MyPage/CartTable.tsx
  src/components/MyPage/MenuTab.tsx
  src/components/common/Button.tsx
  src/pages/Mypage/Cart.tsx
  src/styles/GlobalStyle.tsx
Labels: Priority: High, Type: Feature/Document

#35 Feat: 내가 쓴 리뷰 UXUI 마크업
  index.html
  src/components/MyPage/ReviewBox.tsx
  src/components/common/ProductCard.tsx
  src/pages/Mypage/MyReview.tsx
  src/styles/GlobalStyle.tsx
Labels: Priority: High, Type: Feature/Function

#36 Feature: 회원가입 페이지 마크업 완료
  public/images/signUpUser.png
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Home/Curation.tsx
  src/components/Home/GroupTravel.tsx
  src/components/Home/KV/KVslider.tsx
  src/components/Home/ThemeTravel.tsx
  src/components/Home/TravelEvent.tsx
  src/components/Home/TravelReview.tsx
  src/components/MyPage/CartTable.tsx
  src/components/MyPage/ReviewBox.tsx
  src/components/ProductDetail/ProductCards.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/common/BarTypeItem.tsx
  src/components/common/Button.tsx
  src/components/common/CardTypeItem.tsx
  src/components/common/CheckBox.tsx
  src/components/common/CheckItem.tsx
  src/components/common/Image.tsx
  src/components/common/Input.tsx
  src/components/common/InputBox.tsx
  src/components/common/InputItem.tsx
  src/components/common/ProductCard.tsx
  src/components/common/SelectOptions.tsx
  src/components/common/Title.tsx
  src/pages/Login/index.tsx
  src/pages/Mypage/WishList.tsx
  src/pages/SignUp/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/root.ts
  src/utils/count.ts
Labels: Type: Bug/Function, Type: Bug/UI, Type: Feature/Function

#37 Feat: 홈페이지 이벤트 배너 및 후기, 이벤트 영역 마크업, KV슬라이드 수정
  package-lock.json
  package.json
  public/images/event/_card_review1.png
  public/images/event/_card_review2.png
  public/images/event/_card_review3.png
  public/images/event_banner.png
  public/images/event_banner2.png
  src/components/Home/Banner.tsx
  src/components/Home/GroupTravel.tsx
  src/components/Home/KV/KVslider.tsx
  src/components/Home/KV/Slide.tsx
  src/components/Home/MoreBtn.tsx
  src/components/Home/SlideBanner.tsx
  src/components/Home/ThemeTravel.tsx
  src/components/Home/TravelEvent.tsx
  src/components/Home/TravelReview.tsx
  src/components/common/StarRateWrapGet.tsx
  src/pages/Home/index.tsx
  src/styles/root.ts
Labels: Priority: Medium

#40 Refactor: 타이틀 컴포넌트 수정 및 적용
  src/components/Home/Curation.tsx
  src/components/Home/GroupTravel.tsx
  src/components/Home/ThemeTravel.tsx
  src/components/Home/TravelEvent.tsx
  src/components/Home/TravelReview.tsx
  src/components/MyPage/ReviewBox.tsx
  src/components/ProductDetail/ProductCards.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/common/BarTypeItem.tsx
  src/components/common/Button.tsx
  src/components/common/CardTypeItem.tsx
  src/components/common/Input.tsx
  src/components/common/Title.tsx
  src/pages/SignUp/index.tsx
Labels: Type: Feature/Function

#42 Feat: 상품 상세 페이지 리뷰 컴포넌트
  public/images/product_detail/01_01_하와이와이키키_골프팩_7일.jpg
  public/images/product_detail/01_02_하와이와이키키_골프팩_7일.jpg
  public/images/product_detail/01_04_하와이와이키키_골프팩_7일_01.jpg
  public/images/product_detail/01_04_하와이와이키키_골프팩_7일_02.jpg
  public/images/product_detail/01_04_하와이와이키키_골프팩_7일_03.jpg
  public/images/product_detail/01_04_하와이와이키키_골프팩_7일_04.jpg
  public/images/product_detail/01_05_하와이와이키키_골프팩_7일.jpg
  src/components/Home/TravelReview.tsx
  src/components/ProductDetail/Detail.tsx
  src/components/ProductDetail/MoveTab.tsx
  src/components/ProductDetail/ProductCards.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductDetail/Review.tsx
  src/components/ProductDetail/Reviews.tsx
  src/components/ProductDetail/TravelReview.tsx
  src/components/common/Review.tsx
  src/pages/Product/ProductDetail.tsx
Labels: Priority: High, Type: Feature/Function

#43 Feature: 슬라이드 수정 (슬라이드 텍스트 문구 추가)
  src/components/Home/KV/KVslider.tsx
  src/components/common/Button.tsx
  src/components/common/Image.tsx
  src/components/common/SocialButtons.tsx
  src/pages/SignUp/index.tsx
Labels: Type: Feature/Function

#44 Feature: 그룹별 여행 탭 완료
  src/components/Header.tsx
  src/components/Home/Curation.tsx
  src/components/Home/GroupTravel.tsx
  src/components/Home/KV/KVslider.tsx
  src/components/common/CheckItem.tsx
  src/components/common/Image.tsx
  src/constants/pathConst.ts
  src/pages/Login/index.tsx
  src/pages/SignUp/index.tsx
Labels: Type: Bug/UI, Type: Feature/Function

#46 Feature: 슬라이드 카피 변경
  src/components/Home/KV/KVslider.tsx
  src/components/common/Image.tsx
  src/layout/Section.tsx
Labels: Type: Feature/Function

#47 Fix: Select ui component 수정
  src/components/Home/TravelEvent.tsx
  src/components/common/Select.tsx
  src/components/hooks/useOnClickOutside.ts
Labels: Type: Feature/Function

#51 Feat: 상품 상세 페이지 UXUI 마크업 & 마이 페이지 공통 컴포넌트로 수정
  src/components/ProductDetail/Detail.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductDetail/RelatedProduct.tsx
  src/components/common/Button.tsx
  src/components/common/Image.tsx
  src/components/common/RoundButton.tsx
  src/components/common/SelectOptions.tsx
  src/pages/Mypage/index.tsx
  src/pages/Product/ProductDetail.tsx
Labels: Priority: High, Type: Feature/Function

#54 Feature: select 공통 컴포넌트화 수정 및 적용
  .env
  .gitignore
  src/api/auth.ts
  src/api/instance.ts
  src/api/product.ts
  src/components/Home/Curation.tsx
  src/components/Home/GroupTravel.tsx
  src/components/Home/ThemeTravel.tsx
  src/components/ProductDetail/ProductInfo.tsx
  src/components/ProductDetail/RelatedProduct.tsx
  src/components/common/HeartButton.tsx
  src/components/common/Select.tsx
  src/components/common/SelectOptions.tsx
  src/constants/apiUrlConst.ts
  src/env.d.ts
  src/interfaces/login.ts
  src/interfaces/product.ts
  src/interfaces/signup.ts
  src/pages/Mypage/WishList.tsx
  src/pages/Search/index.tsx
  src/pages/SignUp/index.tsx
Labels: Type: Bug/UI, Type: Feature/Function

#57 Feat: 상품 페이지 UXUI 마크업
  src/components/Header.tsx
  src/components/Theme/MonthProductList.tsx
  src/constants/pathConst.ts
  src/pages/Product/Recommend.tsx
  src/pages/Product/Theme.tsx
  src/router.tsx
Labels: Priority: High, Type: Feature/Function

#60 Feature: 상품 목업데이터 api함수 생성 및 적용
  public/mockData/product.json
  src/api/product.ts
  src/components/Home/Curation.tsx
  src/components/Home/GroupTravel.tsx
  src/components/common/CardTypeItem.tsx
  src/components/common/CheckItem.tsx
  src/components/common/ProductCard.tsx
  src/env.d.ts
  src/interfaces/product.ts
  src/interfaces/signup.ts
  src/pages/Mypage/WishList.tsx
  src/pages/Search/index.tsx
Labels: Status: In Progress, Type: Bug/UI, Type: Feature/Function

#61 Feature: 테마별 인기여행 마크업 진행중
  public/images/themeGolf.png
  src/components/Home/Curation.tsx
  src/components/Home/ThemeTravel.tsx
  src/components/common/BarTypeItem.tsx
  src/components/common/CardTypeItem.tsx
  src/components/common/ProductCard.tsx
  src/layout/Section.tsx
  src/router.tsx
  src/styles/root.ts
Labels: Status: In Progress, Type: Feature/Function

#64 Feat: 상품 페이지 수정
  public/images/all_banner.jpg
  public/images/group_banner.jpg
  public/images/theme_banner.jpg
  src/components/Group/ProductSlider.tsx
  src/components/common/Button.tsx
  src/pages/Product/Group.tsx
  src/pages/Product/Recommend.tsx
  src/pages/Product/Theme.tsx
Labels: Priority: High, Type: Feature/Function

#65 Feature: 홈 테마별 인기여행 마크업 완료
  public/images/themeAmen.jpg
  public/images/themeCulture.jpg
  public/images/themeTracking.jpg
  public/images/themeVacation.jpg
  src/components/Home/KV/KVslider.tsx
  src/components/Home/ThemeTravel.tsx
Labels: Type: Bug/UI, Type: Feature/Function

#68 Feat: 설문조사 결과 페이지 마크업 & 페이지 이동 시 스크롤 상단으로 이동
  src/App.tsx
  src/components/Home/Curation.tsx
  src/components/Survey/Banner.tsx
  src/pages/Survey/Result.tsx
  src/pages/Survey/index.tsx
  src/utils/scrollTop.ts
Labels: Priority: High, Type: Feature/Function

#70 Feature: 그룹별 여행 탭 색상 및 아이콘 적용
  public/images/icons/tabAge5070.png
  public/images/icons/tabAnybody.png
  public/images/icons/tabFamily.png
  public/images/icons/tabFemales.png
  public/images/icons/tabMales.png
  src/components/Home/GroupTravel.tsx
  src/components/Home/KV/KVslider.tsx
  src/components/Home/ThemeTravel.tsx
  src/components/common/CheckItem.tsx
  src/components/common/ProductCard.tsx
  src/pages/Login/index.tsx
  src/styles/root.ts
Labels: Type: Bug/UI, Type: Feature/Function

#76 Feature: 마이페이지 회원정보 수정 마크업완료
  src/components/Header.tsx
  src/components/common/CheckItem.tsx
  src/components/common/GroupTabs.tsx
  src/components/common/HeartButton.tsx
  src/components/common/Input.tsx
  src/components/common/InputItem.tsx
  src/components/common/Select.tsx
  src/components/common/Title.tsx
  src/pages/Login/index.tsx
  src/pages/Mypage/InfoEdit.tsx
  src/pages/Mypage/index.tsx
  src/pages/SignUp/index.tsx
  src/styles/root.ts
Labels: Type: Feature/Function

#77 Feature: 회원 (회원가입, 로그인, 로그아웃, 회원정보, 회원정보 수정, 회원탈퇴) api 설정
  .env
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/instance.ts
  src/constants/apiUrlConst.ts
  src/utils/cookie.ts
Labels: Priority: High, Type: Feature/Function

#79 Feat: 관리자 상품 관련 페이지 마크업
  .gitignore
  index.html
  public/mockData/category.json
  src/components/common/Button.tsx
  src/constants/pathConst.ts
  src/pages/AddProduct/index.tsx
  src/pages/Admin/index.tsx
  src/pages/EditProduct/index.tsx
  src/pages/ProductsList/index.tsx
  src/pages/UserList/index.tsx
  src/router.tsx
  src/styles/root.ts
  tsconfig.json
Labels: Priority: High, Type: Feature/Function
